# Alternative Firebase Hosting preview deployment using CLI token
# Use this if you prefer not to use Service Account

name: Deploy to Firebase Hosting on PR (Token)
on: 
  pull_request:
    branches:
      - main
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test -- --watchAll=false --passWithNoTests
        env:
          CI: true
      
      - name: Build application
        run: npm run build
        env:
          CI: true
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Deploy preview to Firebase Hosting
        run: |
          firebase hosting:channel:deploy pr-${{ github.event.number }} --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_PROJECT: troop-468-manager
      
      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview deployed to Firebase Hosting!\n\n📱 **Preview URL**: https://troop-468-manager--pr-${{ github.event.number }}-preview.web.app\n\n*This preview will be available for 7 days.*'
            })
